FROM python:3.14

WORKDIR /container

COPY ./requirements.txt ./container/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./api ./container/api

CMD ["fastapi", "run", "api/main.py", "--port", "8000"]