FROM python:3.14

COPY ./requirements.txt ./container/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /container/requirements.txt

COPY --chmod=777 ./api ./container/api

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -yq --no-install-recommends install sqlite3 && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /container

CMD ["fastapi", "run", "api/main.py", "--port", "8000"]
