FROM python:3.14

COPY ./requirements.txt ./container/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /container/requirements.txt

COPY --chmod=777 ./api ./container/api

WORKDIR /container

CMD ["fastapi", "run", "api/main.py", "--port", "8000"]
